spring:
  application:
    name: CUSTOMER-SERVICE
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
couchbase:
  bucket: bucket
  url: localhost
  username: Administrator
  password: 123456
server:
  port: 9091