spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:9091
          predicates:
            - Path=/customer-service/**
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
server:
  port: 9090